build:
  nodes:
    node-that-needs-docker:
      environment:
        docker:
          remote_engine: true
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: .coverage/clover.xml
              format: clover