build:
  my-node:
    services:
      mongo: 4
  nodes:
    coverage:
      tests:
        override:
          - command: npm run test:ci
            coverage:
              file: .coverage/clover.xml
              format: clover