version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run tests"
          command: npm test
      - store_artifacts:
          path: .coverage
